# Generated by Django 4.2.20 on 2025-05-01 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='financialmodel',
            name='model_type',
            field=models.CharField(choices=[('DCF', 'Discounted Cash Flow'), ('Forecast', 'Forecast Model'), ('Budget', 'Budgeting Model'), ('Scenario', 'Scenario Analysis'), ('CashFlow', 'Cash Flow Model'), ('Valuation', 'Valuation Model'), ('LBO', 'Leveraged Buyout Model'), ('M&A', 'M&A Model'), ('Sensitivity', 'Sensitivity Analysis'), ('BreakEven', 'Break-Even Model'), ('KPI', 'KPI Dashboard'), ('3Statement', '3-Statement Model'), ('Rolling', 'Rolling Forecast'), ('CapTable', 'Capitalization Table'), ('MonteCarlo', 'Monte Carlo Simulation'), ('IRR', 'Internal Rate of Return Model')], max_length=20),
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='forecasting.financialmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Revenue', 'Revenue'), ('Expense', 'Expense'), ('Asset', 'Asset'), ('Liability', 'Liability'), ('Equity', 'Equity'), ('Other', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='forecasting.financialmodel')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasting.period')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasting.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='Assumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unit', models.CharField(default='%', max_length=20)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assumptions', to='forecasting.financialmodel')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasting.scenario')),
            ],
        ),
    ]
