# Generated by Django 4.2.20 on 2025-05-02 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forecasting', '0002_period_alter_financialmodel_model_type_scenario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
